console.log("/**    王涛是小猪猪！           _");
console.log(" *  _._ _..._ .-\',     _.._(`))");
console.log(" * \'-. `     \'  /-._.-\'    \',/");
console.log(" *    )         \/\/            \'.");
console.log(" *   / _    _    |             \/\/");
console.log(" *  |  a    a    /              |");
console.log(" *  \/\/   .-.                     ;");
console.log(" *   \'-(\'\' ).-\'       ,\'       ;");
console.log(" *      \'-;           |      .\'");
console.log(" *         \/\/           \/\/    /");
console.log(" *         | 7  .__  _.-\/\/   \/\/");
console.log(" *         | |  |  ``/  /`  /");
console.log(" *        /,_|  |   /,_/   /");
console.log(" *           /,_/      \'`-\'");
console.log(" */");
console.log("");
