console.log("/**");
console.log(" *           _.._        ,------------.");
console.log(" *        ,\'      `.    ( 张诚铭，I want you! )");
console.log(" *       /  __) __` \/\/    `-,----------\'");
console.log(" *      (  (`-`(-\')  ) _.-\'");
console.log(" *      /)  \/\/  = /  (");
console.log(" *     /\'    |--\' .  \/\/");
console.log(" *    (  ,---|  `-.)__`");
console.log(" *     )(  `-.,--\'   _`-.");
console.log(" *    \'/,\'          (  Uu\',");
console.log(" *     (_       ,    `/,-\' )");
console.log(" *     `.__,  : `-\'/  /`--\'");
console.log(" *       |     `--\'  |");
console.log(" *       `   `-._   /");
console.log(" *        \/\/        (");
console.log(" *        /\/\/ .      \/\/.  ");
console.log(" *       / |` \/\/     ,-\/\/");
console.log(" *      /  \/\/| .)   /   \/\/");
console.log(" *     ( ,\'|\/\/    ,\'     :");
console.log(" *     | \/\/,`.`--\'/      }");
console.log(" *     `,\'    \/\/  |,\'    /");
console.log(" *    / \'-._   `-/      |");
console.log(" *    \'-.   \'-.,\'|     ;");
console.log(" *   /        _/[\'---\'\'\']");
console.log(" *  :        /  |\'-     \'");
console.log(" *  \'           |      /");
console.log(" *              `      |");
console.log(" */");